// Copyright © 2024-2026 The µcad authors <info@microcad.xyz>
// SPDX-License-Identifier: AGPL-3.0-or-later

//! Generate tests out of *Markdown* files which include µcad code
//!
//! Path will be scanned recursively for *Markdown* files (`*.md`).
//! Code must be marked by *Markdown* code markers (code type: `µcad`) with a test ID attached.
//! In case of a failing test `#fail` must be appended to the test ID.
//!
//! Relative path's of scanned folder names will be used to build a modules structure
//! in the resulting code.
//! If test IDs include `.` name will be split into several names which will be
//! used to crates sub modules.

use microcad_lang_markdown::MdBook;
use microcad_test_tools::{output::*, test_env::*};
use miette::{Context, IntoDiagnostic, Result};
use std::{io::Write, path::Path};

/// for debugging purpose
#[allow(unused)]
macro_rules! warning {
    ($($tokens: tt)*) => {
        // HINT: switch `note` -> `warning` to activate debug messages
        println!("cargo:note={}", format!($($tokens)*))
    }
}

/// Generate tests from the *Markdown* files which are within the given `path`
///
/// Path will be scanned recursively
pub fn generate(
    path: impl AsRef<Path>,
    out_file: impl AsRef<Path>,
    test_list_file: impl AsRef<Path>,
) -> Result<()> {
    use std::*;

    // get target path
    let out_dir = env::var("OUT_DIR").into_diagnostic()?;
    let dest_path = path::Path::new(&out_dir).join(out_file);
    // we will create a single output file whose content will be written into this variable first
    let mut code = String::from(
        r#"// This code was generated by microcad_markdown_test
// Copyright © 2026 The µcad authors <info@microcad.xyz>
// SPDX-License-Identifier: AGPL-3.0-or-later


"#,
    );

    // read all *Markdown files and write result into `code`
    let test_outputs = generate_test_outputs(&mut code, &path);

    create_test_list(test_list_file, &test_outputs);

    // remove any previous banners
    remove_banners(path, &test_outputs)?;

    fs::write(&dest_path, code)
        .into_diagnostic()
        .context(format!("cannot create file '{dest_path:?}'"))
}

fn generate_test_outputs(code: &mut String, path: impl AsRef<Path>) -> Vec<TestOutput> {
    let mdbook = MdBook::new(path).expect("No error");
    let mut outputs = Vec::new();

    let mut root = TestModule::default();

    let mut paths = std::collections::HashSet::new();

    mdbook.code_blocks().for_each(|(path, code_block)| {
        let header = &code_block.header;
        warning!("{header}");

        let mut name = match (&header.name, &header.fragment) {
            (None, _) => {
                // We need a name
                return;
            }
            (Some(name), None) => name.clone(),
            (Some(name), Some(fragment)) => format!("{name}#{fragment}"),
        };
        if !header.parameters.is_empty() {
            name += &format!("({})", header.parameters.join(","));
        }

        let env = TestEnv::new(
            &mdbook.abs_md_file(&path),
            &name,
            &code_block.code,
            (code_block.line_offset + 1) as u32,
        );

        let mut current = &mut root;

        // Iterate through path components
        for component in path.components() {
            let name = component.as_os_str().to_string_lossy().into_owned();

            // Traverse deeper into the tree, creating modules if they don't exist
            current = current.submodules.entry(name).or_default();
        }

        paths.insert(path.clone());

        let output = env.output();
        // Now 'current' is the specific leaf module for this path
        current.outputs.push((env.test_code(), output.clone()));
        outputs.push(output);
    });

    code.push_str(&root.test_code("tests"));

    // Watch md files for changes
    for path in paths {
        println!("cargo:rerun-if-changed={}", path.display());
    }

    outputs
}

fn create_test_list(path: impl AsRef<std::path::Path>, outputs: &[TestOutput]) {
    let mut seen = std::collections::HashSet::new();
    for item in outputs.iter().map(|o| &o.name) {
        if !seen.insert(item) {
            panic!("doublet test name '{item}' in {:?}", path.as_ref())
        }
    }

    std::fs::File::create(path.as_ref())
        .expect("file access error")
        .write_all(make_test_list(&path, outputs).as_bytes())
        .expect("write error");
    // tell cargo to watch this file
    println!("cargo:rerun-if-changed={}", path.as_ref().display());
}

fn make_test_list(path: impl AsRef<std::path::Path>, tests: &[TestOutput]) -> String {
    let count = tests.len();
    let mut result = format!(
        "# Test List

The following table lists all tests included in this documentation.

**{count}** tests have been evaluated with version **{version}** of microcad.

Click on the test names to jump to file with the test or click the buttons to get the logs.

| Result | Source | Name |
|-------:|--------|------|
",
        version = env!("CARGO_PKG_VERSION")
    );

    {
        let mut tests = tests.iter().collect::<Vec<_>>().clone();
        tests.sort();
        tests.iter().for_each(|test| {
            result.push_str(&test.table_row(path.as_ref().parent().expect("invalid path")));
        });
    }

    result
}

/// Remove all banners in `path` and exclude folders whose names are contained
/// in `exclude_dirs` from search.
fn remove_banners(path: impl AsRef<Path>, exclude_outputs: &[TestOutput]) -> Result<()> {
    //warning!("remove_banners: {:?} {exclude_files:?}", path.as_ref());
    for entry in std::fs::read_dir(&path).into_diagnostic()?.flatten() {
        // get file type
        if let Ok(file_type) = entry.file_type() {
            // check if directory or file
            if file_type.is_dir() {
                if entry.file_name() == ".test" {
                    clean_dir(entry.path(), exclude_outputs)?;
                } else {
                    remove_banners(entry.path(), exclude_outputs)?;
                }
            }
        }
    }

    Ok(())
}

/// Remove all files within `.test` directory
fn clean_dir(path: impl AsRef<Path>, exclude_files: &[TestOutput]) -> Result<()> {
    warning!("remove banners in: {:?}", path.as_ref());

    // list all files within `.test` directory and remove them
    for entry in std::fs::read_dir(&path)
        .unwrap()
        .flatten()
        .filter(|entry| entry.file_type().unwrap().is_file())
    {
        if 0 == exclude_files
            .iter()
            .filter(|f| f.has_path(&entry.path()))
            .count()
        {
            // warning!("remove: {:?}", entry.path());
            std::fs::remove_file(entry.path()).into_diagnostic()?;
        }
    }
    Ok(())
}
