# Copyright © 2025-2026 The µcad authors <info@microcad.xyz>
# SPDX-License-Identifier: AGPL-3.0-or-later

id = "microcad"
name = "Microcad"
version = "0.0.1"
schema_version = 1
authors = ["Michael Winkelmann"]
description = "Microcad Plugin for Zed"
repository = "https://codeberg.org/microcad/microcad"

[grammars.microcad]
repository = "https://codeberg.org/microcad/tree-sitter-microcad"
commit = "339420b9cfbb9d6e96ed1f881c1632af4c3fcd22"

[language_servers.microcad-lsp]
language = "Microcad"
