#matrix:
#  RUST: [stable, beta, nightly]

clone:
  - name: git
    image: woodpeckerci/plugin-git
    settings:
      partial: false
      depth: 0

steps:
  test:
    when:
      event: [pull_request]
    image: rust
    environment:
      CARGO_TERM_COLOR: always
    commands:
      - apt-get update && apt-get install -y ninja-build cmake
      - rustup default $RUST
      - rustup component add rustfmt
      - cargo check -j $(nproc)
      - COPYRIGHT_CHECK=1 cargo test -j $(nproc)
