// Copyright © 2025-2026 The µcad authors <info@microcad.xyz>
// SPDX-License-Identifier: AGPL-3.0-or-later

//! Implementation for the `#[test_builtin_fn(...)` attribute macro.

use crate::prelude::*;

// Represents a single key-value argument pair: `lhs = 3`
struct TestArg {
    name: Ident,
    value: Expr,
}

impl Parse for TestArg {
    fn parse(input: ParseStream) -> Result<Self> {
        let name: Ident = input.parse()?;
        input.parse::<Token![=]>()?;
        let value: Expr = input.parse()?;
        Ok(TestArg { name, value })
    }
}

// Parses the macro attribute content: `core::greater_than(lhs = 3, rhs = 5) => Ok(false)`
struct TestBuiltinFnAttr {
    func_path: Path,
    args: Vec<TestArg>,
    expected: Expr,
}

impl Parse for TestBuiltinFnAttr {
    fn parse(input: ParseStream) -> Result<Self> {
        let func_path: Path = input.parse()?;

        // Parse `(lhs = 3, rhs = 5)`
        let content;
        syn::parenthesized!(content in input);

        let mut args = Vec::new();
        while !content.is_empty() {
            args.push(content.parse::<TestArg>()?);
            if content.peek(Token![,]) {
                content.parse::<Token![,]>()?;
            } else {
                break;
            }
        }

        // Parse `== expected`
        let (_, expected) = (input.parse::<Token![==]>()?, input.parse()?);

        Ok(TestBuiltinFnAttr {
            func_path,
            args,
            expected,
        })
    }
}

pub fn test_builtin_fn_impl(attr: TokenStream, item: TokenStream) -> TokenStream {
    // Parse the attribute input
    let TestBuiltinFnAttr {
        func_path,
        args,
        expected,
    } = parse_macro_input!(attr as TestBuiltinFnAttr);

    // Parse the function item
    let mut input_fn = parse_macro_input!(item as ItemFn);

    let arg_names = args.iter().map(|a| &a.name);
    let arg_values = args.iter().map(|a| &a.value);

    // Construct the single assert statement generated by this attribute invocation
    let assertion = quote! {
        assert_eq!(
            #func_path(microcad_lang_types::arguments!(#(#arg_names = #arg_values),*), &mut context).unwrap(),
            microcad_lang_types::Value::from(#expected)
        );
    };

    // Inject context creation if it's not already in the function body
    let has_context = input_fn
        .block
        .stmts
        .iter()
        .any(|stmt| quote!(#stmt).to_string().contains("context"));

    if !has_context {
        input_fn.block.stmts.push(syn::parse_quote! {
            let mut context = microcad_builtin::BuiltinEvalContext::default();
        });
    }
    // Inject the assertion at the top of the function body
    input_fn.block.stmts.push(syn::parse_quote! { #assertion });

    quote! {
        #input_fn
    }
    .into()
}
