# Copyright © 2026 The µcad authors <info@ucad.xyz>
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "microcad-docgen"
description = "µcad Documentation Generators"
documentation = "https://docs.rs/microcad-docgen"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
derive_more = { version = "2", features = ["deref", "deref_mut", "from"] }
log = "0.4"
miette = "7.3.0"
serde = "1.0"
thiserror = "2.0"
toml = { version = "1.1.2", features = ["serde"] }

# Used by bin_builtin
clap = { version = "4", features = ["derive"], optional = true }

microcad-builtin = { workspace = true }
microcad-lang-markdown = { workspace = true }
microcad-lang-resolve = { workspace = true }

[[bin]]
name = "microcad-docgen-builtin"
path = "builtin.rs"
required-features = ["bin_builtin"]

[features]
# Dependencies for md extractor
bin_builtin = ["dep:clap"]
