import {
    ListView,
    VerticalBox,
    Button,
    HorizontalBox,
} from "std-widgets.slint";




export struct VM_Argument {
    id: string,
    value: string,
}

export struct VM_Creator {
    symbol_name: string,
}

export struct VM_Item {
    depth: int,
    element: string,
    src_ref: string,
    creator: VM_Creator,
}



component ListItem inherits Rectangle {
    in property <VM_Item> item;
    in property <int> index: 0;

    height: 40px;
    border-radius: 4px;
    background: Math.mod(self.index, 2) == 0 ? #f0f0f0 : #e0e0e0;
    Rectangle {
        // Hover effect
        background: touch-area.has-hover ? #cce5ff : transparent;
        width: root.width;
        height: root.height;
    }

    HorizontalLayout {
        width: root.width;
        height: root.height;

        Rectangle {
            width: item.depth * 32px;
        }

        Text {
            text: item.element;
            vertical-alignment: center;
            horizontal-alignment: left;
            font-size: 16px;
            font-weight: 600;
        }
    }

    touch-area := TouchArea {
        width: root.width;
        height: root.height;
    }
}

component View3DControlPanel {
    callback button-launch-3d-view-clicked <=> button-launch-3d-view.clicked;

    VerticalLayout {
        button-launch-3d-view := Button {
            text: @tr("Launch 3D View");
        }
    }
}

export component MainWindow inherits Window {
    callback button-launch-3d-view-clicked <=> control-panel.button-launch-3d-view-clicked;
    in property <[VM_Item]> view-model;

    title: "µcad Inspector";
    default-font-family: "Jetbrains Mono";
    preferred-width: 1024px;
    preferred-height: 1024px;

    HorizontalBox {
        width: parent.width;
        height: parent.height;

        list-view := ListView {
            mouse-drag-pan-enabled: true;
            for item[index] in root.view-model: ListItem {
                width: list-view.viewport-width;
                item: item;
                index: index;
            }
        }

        control-panel := View3DControlPanel { }
    }
}
