import {
    ListView,
    VerticalBox,
    Button,
    HorizontalBox,
    TextEdit,
} from "std-widgets.slint";




export struct VM_Argument {
    id: string,
    value: string,
}

export struct VM_Creator {
    symbol_name: string,
}


export struct SymbolTreeModelItem {
    depth: int,
    name: string,
}

export struct ModelTreeModelItem {
    depth: int,
    element: string,
    src_ref: string,
    creator: VM_Creator,
}


component TreeViewItem inherits Rectangle {
    in property <int> index: 0;

    height: 40px;
    border-radius: 4px;
    background: Math.mod(self.index, 2) == 0 ? #f0f0f0 : #e0e0e0;
    Rectangle {
        // Hover effect
        background: touch-area.has-hover ? #cce5ff : transparent;
        width: root.width;
        height: root.height;
    }

    HorizontalLayout {
        width: root.width;
        height: root.height;
        @children
    }

    touch-area := TouchArea {
        width: root.width;
        height: root.height;
    }
}

component ModelTreeViewItem inherits TreeViewItem {
    in property <ModelTreeModelItem> item;

    Rectangle {
        width: item.depth * 32px;
    }

    Text {
        text: item.element;
        vertical-alignment: center;
        horizontal-alignment: left;
        font-size: 16px;
        font-weight: 600;
    }
}

component SymbolTreeViewItem inherits TreeViewItem {
    in property <SymbolTreeModelItem> item;

    Rectangle {
        width: item.depth * 32px;
    }

    Text {
        text: item.name;
        vertical-alignment: center;
        horizontal-alignment: left;
        font-size: 16px;
        font-weight: 600;
    }
}

component ControlPanel {
    callback button-launch-viewer-clicked <=> button-launch-viewer.clicked;
    callback button-send-source-code-clicked <=> button-send-source-code.clicked;

    VerticalLayout {
        button-launch-viewer := Button {
            text: @tr("Launch 3D View");
        }

        button-send-source-code := Button {
            text: @tr("Send source code");
        }
    }
}

export component MainWindow inherits Window {
    callback button-launch-viewer-clicked <=> control-panel.button-launch-viewer-clicked;
    callback button-send-source-code-clicked <=> control-panel.button-send-source-code-clicked;
    in-out property source-code <=> source-code-view.text;
    in property <[ModelTreeModelItem]> model-tree;
    in property <[SymbolTreeModelItem]> symbol-tree;

    title: "µcad Inspector";
    default-font-family: "Jetbrains Mono";
    preferred-width: 1024px;
    preferred-height: 1024px;

    VerticalBox {
        width: parent.width;
        height: parent.height;

        HorizontalBox {
            source-code-view := TextEdit { }

            symbol-tree-view := ListView {
                mouse-drag-pan-enabled: true;
                for item[index] in root.symbol-tree: SymbolTreeViewItem {
                    width: symbol-tree-view.viewport-width;
                    item: item;
                    index: index;
                }
            }

            model-tree-view := ListView {
                mouse-drag-pan-enabled: true;
                for item[index] in root.model-tree: ModelTreeViewItem {
                    width: model-tree-view.viewport-width;
                    item: item;
                    index: index;
                }
            }
        }

        control-panel := ControlPanel { }
    }
}
