
export struct VM_Argument {
    id: string,
    value: string,
}

export struct VM_SrcRef {
    line: int,
    col: int,
    source_hash: string, 
}


export struct VM_DocBlock {
    summary: string,
    details: string,
    src_ref: VM_SrcRef,
}

export struct VM_SymbolInfo {
    id: string,
    kind: string,
    doc: VM_DocBlock,
    // TODO: signatures: [VM_Signatures]
    src_ref: VM_SrcRef, 
}

export struct VM_Creator {
    symbol: VM_SymbolInfo,
    src_ref: VM_SrcRef,
}

/// Wrapper to map a model::Element into slint viewmodel Element
export struct VM_Element {
    name: string,
    src_ref: VM_SrcRef,
}

/// Current state of the view
export struct VM_State {
    current_source_hash: string,
    current_line: int,
}