
export struct VM_Argument {
    id: string,
    value: string,
}

export struct VM_SrcRef {
    line: int,
    col: int,
    source_hash: string, 
}


export struct VM_DocBlock {
    summary: string,
    details: string,
    src_ref: VM_SrcRef,
}

export struct VM_SymbolInfo {
    id: string,
    kind: string,
    doc: VM_DocBlock,
    // signatures: [VM_Signatures]
    src_ref: VM_SrcRef, 
}

export struct VM_Creator {
    symbol: VM_SymbolInfo,
    src_ref: VM_SrcRef,
}

export struct VM_Element {
    name: string,
    src_ref: VM_SrcRef,
}