# Copyright © 2024-2026 The µcad authors <info@microcad.xyz>
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "microcad-builtin"
description = "Provides the built-in functionalities available in the µcad language."
documentation = "https://docs.rs/microcad-std"
edition.workspace = true
rust-version.workspace = true
version.workspace = true
license = "AGPL-3.0-or-later"

[dependencies]
log = "0.4"
cgmath = "0.18"
derive_more = { version = "2", features = ["deref", "deref_mut", "from", "display", "debug"] }
dirs = "6"
geo = "0.33"
phf = { version = "0.14", features = ["macros"] }
thiserror = "2.0"

microcad-lang-base = { workspace = true }
microcad-lang-types = { workspace = true }
microcad-builtin-proc-macros = { workspace = true }
