// Copyright © 2025 The µcad authors <info@microcad.xyz>
// SPDX-License-Identifier: AGPL-3.0-or-later

import {
    ListView,
    VerticalBox,
    Button,
    HorizontalBox,
    TextEdit,
    Palette,
} from "std-widgets.slint";

import {
    VM_Creator,
    VM_DocBlock,
    VM_Element,
    VM_SrcRef,
    VM_State,
    VM_SymbolInfo,
} from "viewmodel.slint";

// Model item for a single line of code.
export struct SourceCodeModelItem {
    line: string,
    line_number: int,
    byte_range_start: int,
    byte_range_end: int,
    selected: bool,
}

export struct SymbolTreeModelItem {
    depth: int,
    name: string,
    source_hash: int,
}

export struct ModelTreeModelItem {
    depth: int,
    element: VM_Element,
    creator: VM_Creator,
}


component ViewItem inherits Rectangle {
    in property <int> index: 0;
    in property <bool> is-selectable;
    in-out property <bool> is-selected;

    callback is-selected-changed;
    callback selected();

    height: 32px;
    border-radius: 4px;
    background: Math.mod(self.index, 2) == 0 ? #f0f0f0 : #e0e0e0;
    Rectangle {
        // Hover effect
      //  background: touch-area.has-hover ? #cce5ff : transparent;
        width: root.width;
        height: root.height;
    }

    HorizontalLayout {
        width: root.width;
        height: root.height;
        @children
    }
}

component SourceCodeViewItem inherits Rectangle {
    in property <SourceCodeModelItem> item;
    in property <int> index: 0;

    in-out property <VM-State> state;
    callback clicked(src_ref: VM-SrcRef);

    height: 20px;

    HorizontalLayout {
        width: root.width;
        height: root.height;

        Rectangle {
            background: #e0e0e0;
            height: root.height;
            width: 32px;

            Text {
                height: parent.height;
                text: item.line-number + 1;
                vertical-alignment: center;
                horizontal-alignment: left;
                font-weight: 600;
            }
        }

        Text {
            text: item.line;
            height: 20px;
            y: 4px;
            horizontal-alignment: left;
        }
    }

    Rectangle {
        width: root.width;
        height: root.height;
        background: transparent;
        visible: root.state.current-line == item.line_number + 1;
        border-color: black;
        border-width: 1px;
    }

    TouchArea {
        width: root.width;
        height: root.height;
        clicked => {
            let src-ref: VM-SrcRef = { line: item.line_number, col: 1, source-hash: state.current-source-hash };
            root.state.current-line = item.line-number + 1;
            debug(src-ref);
            root.clicked(src-ref);
        }
    }
}

component SymbolTreeViewItem inherits ViewItem {
    in property <SymbolTreeModelItem> item;

    Rectangle {
        width: item.depth * 32px;
    }

    Text {
        text: item.name;
        vertical-alignment: center;
        horizontal-alignment: left;
        font-size: 16px;
        font-weight: 600;
    }
}

component LineNumberItem inherits Rectangle {
    in property <VM-SrcRef> src_ref;
    in property <VM-State> state;

    callback clicked(src_ref: VM-SrcRef);

    width: 32px;
    border-width: state.current-line == src_ref.line ? 1px : 0px;
    border-color: black;

    Text {
        text: src-ref.line;
        vertical-alignment: center;
        horizontal-alignment: left;
        font-size: 12px;
        font-weight: 600;
        visible: state.current_source_hash == src_ref.source-hash && src-ref.line > 0;
    }

    TouchArea {
        width: root.width;
        height: root.height;
        enabled: root.src_ref.source-hash == root.state.current-source-hash;
        clicked => {
            debug(root.src_ref);
            root.clicked(root.src_ref);
        }
    }
}

component ModelTreeViewItem inherits ViewItem {
    in property <ModelTreeModelItem> item;
    in property <VM-State> state;
    is-selectable: true;
    callback src_ref_clicked(src-ref: VM-SrcRef);

    element-info := LineNumberItem {
        src_ref: root.item.element.src_ref;
        state: root.state;
        background: self.src_ref.source-hash == state.current-source-hash ? #6d85ee : transparent;
        clicked(src-ref) => {
            root.selected();
            root.src_ref_clicked(src-ref);
        }
    }

    creator-info := LineNumberItem {
        src_ref: root.item.creator.src_ref;
        state: root.state;
        background: self.src_ref.source-hash == state.current-source-hash ? #6deec3 : transparent;

        clicked(src-ref) => {
            root.selected();
            root.src_ref_clicked(src-ref);
        }
    }

    Rectangle {
        width: item.depth * 32px;
    }

    Text {
        text: item.element.name;
        vertical-alignment: center;
        horizontal-alignment: left;
        font-size: 16px;
        font-weight: 600;
    }
}

component ControlPanel {
    callback button-launch-viewer-clicked <=> button-launch-viewer.clicked;
    callback button-send-source-code-clicked <=> button-send-source-code.clicked;

    VerticalLayout {
        button-launch-viewer := Button {
            text: @tr("Launch 3D View");
        }

        button-send-source-code := Button {
            text: @tr("Send source code");
        }
    }
}

export component MainWindow inherits Window {
    callback button-launch-viewer-clicked <=> control-panel.button-launch-viewer-clicked;
    callback button-send-source-code-clicked <=> control-panel.button-send-source-code-clicked;
    callback src_ref_clicked(src-ref: VM-SrcRef);

    in property <string> source-code;
    in property <[SourceCodeModelItem]> source-code-model;
    in property <[ModelTreeModelItem]> model-tree;
    in property <[SymbolTreeModelItem]> symbol-tree;
    in-out property <VM-State> state;

    src_ref_clicked(src_ref) => {
        root.state.current-line = src-ref.line;
        debug("Current line: {}", root.state.current-line);
    }

    title: "µcad Inspector";
    default-font-family: "Jetbrains Mono";
    preferred-width: 1024px;
    preferred-height: 1024px;

    VerticalBox {
        width: parent.width;
        height: parent.height;

        HorizontalBox {
            source-code-view := ListView {
                mouse-drag-pan-enabled: true;
                for item[index] in root.source-code-model: SourceCodeViewItem {

                    clicked => {
                        debug("Hello {}", item.line-number);
                    }
                    height: 20px;
                    width: symbol-tree-view.viewport-width;
                    item: item;
                    state <=> root.state;
                    index: index;
                }
            }

            symbol-tree-view := ListView {
                mouse-drag-pan-enabled: true;
                for item[index] in root.symbol-tree: SymbolTreeViewItem {
                    width: symbol-tree-view.viewport-width;
                    item: item;
                    index: index;
                }
            }

            model-tree-view := ListView {
                mouse-drag-pan-enabled: true;
                for item[index] in root.model-tree: ModelTreeViewItem {
                    width: model-tree-view.viewport-width;
                    item: item;
                    state <=> root.state;
                    index: index;
                    src_ref_clicked(src-ref) => {
                        root.src_ref_clicked(src-ref)
                    }
                }
            }
        }

        control-panel := ControlPanel { }
    }
}
